### ISSUE TITLE
Доработать/починить/переписать отладчик

### ISSUE THREAD

**Issue by vslutov** [cmc-python/modelmachine#4]
- continue
- убрать python stack trace, добавить перехват исключений при неправильных адресах
- IP -> PC IR-> RI
- ведущие нули в состоянии регистров

**Comment by FrBrGeorge** [comment]
- Использовать readline в отладчике, получим забесплатно историю команд и редактор
- Выводить какую-нибудь подсказку, а то дискомфортно: кажется, что висит

**Comment by vslutov** [comment]
- Добавить состояние "остановлена с ошибкой"
