### ISSUE TITLE
Приделать Travis CI

### ISSUE THREAD

**Issue by spacediver** [cmc-python/modelmachine#7]
Как я понимаю, юнит-тесты присутствуют, поэтому вполне стоит это сделать. Для опенсорсных проектов Travis бесплатный, и натурально интегрируется с github'ом. Будем иметь CI-статус всех коммитов.

**Comment by vslutov** [comment]
Вроде добавил и вроде работает.
https://github.com/cmc-python/modelmachine/pull/8
