### ISSUE TITLE
Разрешить комментарии во всех секциях

### ISSUE THREAD

**Issue by FrBrGeorge** [cmc-python/modelmachine#7]
Было бы хорошо, чтобы вот такой код оказался валидным
`
mm3
; данная программа будет считать дискриминант
; b*_2 - 4_a*c
[config]
; a,b,c
input = 0x100, 0x101, 0x102 ; a,b,c
output = 0x105 ; d

[code]
; тут пишем код
03 0101 0101 0103; b^2:  03 - умножение(без знака), 0101 - ячейка, в которой лежит b, а в 0102 мы пишем результат
03 0100 0102 0104; a_c
03 0005 0104 0104; 4_a_c, 0005 - это адоес константы 4;
02 0103 0104 0105; b^2-4_a*c:  02 - вычитание
99 0000 0000 0000; 99 - код остановки программы
00000000000004   ; а здесь описана константа 4

[input]
; a,b,c
1 2 1
`

**Comment by vslutov** [comment]
Теперь валидно. Положить в примеры?

**Comment by FrBrGeorge** [comment]
Хорошо бы!
